import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import net from "node:net";
import tls from "node:tls";
import { config } from "./config.js";

export type ProxyProtocol = "http" | "https" | "socks5";
export interface ProxyRecord { id:string; endpoint:string; protocol:ProxyProtocol; country:string; code:string; flag:string; health:number; host:string; port:number; username:string; password:string }
export interface SafeProxy { id:string; country:string; code:string; flag:string }
const FILE=process.env.LUMEN_PROXY_CATALOG_FILE||"/data/proxy.txt";
const TTL=10*60_000;
const CODES:Record<string,string>={india:"IN",colombia:"CO",peru:"PE",iceland:"IS",singapore:"SG",ecuador:"EC",germany:"DE",albania:"AL",france:"FR",netherlands:"NL",unitedstates:"US",canada:"CA",japan:"JP",turkey:"TR",russia:"RU",finland:"FI",sweden:"SE",norway:"NO",switzerland:"CH",austria:"AT",italy:"IT",spain:"ES",brazil:"BR",argentina:"AR",chile:"CL",mexico:"MX",australia:"AU",hongkong:"HK",taiwan:"TW",southkorea:"KR",unitedkingdom:"GB"};
const flag=(c:string)=>[...c].map(x=>String.fromCodePoint(127397+x.charCodeAt(0))).join("");
const codeFor=(n:string)=>CODES[n.toLowerCase().replace(/[^a-z]/g,"")]||"ZZ";
function parseEndpoint(source:string,country:string,health:number):ProxyRecord{const u=new URL(source);const protocol=u.protocol.slice(0,-1) as ProxyProtocol;if(!["http","https","socks5"].includes(protocol)||!u.hostname)throw Error("unsupported proxy protocol");const authority=source.slice(source.indexOf("//")+2).split(/[/?#]/,1)[0];const pm=authority.match(/:(\d+)$/);const port=Number(u.port||pm?.[1]||0);if(!port||port>65535)throw Error("invalid proxy port");const endpoint=`${protocol}://${u.username?encodeURIComponent(decodeURIComponent(u.username))+(u.password?":"+encodeURIComponent(decodeURIComponent(u.password)):"")+"@":""}${u.hostname.includes(":")?`[${u.hostname}]`:u.hostname}:${port}`;const id=crypto.createHash("sha256").update("lumen-managed-v15"+endpoint).digest("hex").slice(0,24);const code=codeFor(country);return{id,endpoint,protocol,country,code,flag:code==="ZZ"?"🌐":flag(code),health:Math.max(0,Math.min(100,health)),host:u.hostname,port,username:decodeURIComponent(u.username),password:decodeURIComponent(u.password)}}
export function parseCatalogText(text:string):ProxyRecord[]{const out:ProxyRecord[]=[];const seen=new Set<string>();for(const rawLine of text.split(/\r?\n/)){const line=rawLine.trim();if(!line||line.startsWith(";")||line.startsWith("//"))continue;const urlMatch=line.match(/(?:https?|socks5):\/\/[^\s\])]+/i);if(!urlMatch)continue;const tail=line.slice((urlMatch.index||0)+urlMatch[0].length);const hash=urlMatch[0].lastIndexOf("#");let source=urlMatch[0],country="";if(hash>=0){country=decodeURIComponent(source.slice(hash+1));source=source.slice(0,hash)}const meta=(country+tail).match(/^\s*([^\]-]+?)\s*(?:\]|\))?\s*-\s*(\d{1,3})\s*%/);if(!meta)continue;try{const rec=parseEndpoint(source,meta[1].trim(),Number(meta[2]));if(!seen.has(rec.id)){seen.add(rec.id);out.push(rec)}}catch{}}return out}
function load(){const env=process.env.LUMEN_PROXY_CATALOG_JSON||"";try{return parseCatalogText(env.trim()?env:fs.readFileSync(FILE,"utf8"))}catch{return []}}
export function importCatalogText(text:string){if(typeof text!=="string"||text.length>2_000_000)throw Error("invalid proxy text");const rows=parseCatalogText(text);if(!rows.length)throw Error("no valid proxies found");fs.mkdirSync(path.dirname(FILE),{recursive:true});fs.writeFileSync(FILE+".tmp",text,{mode:0o600});fs.renameSync(FILE+".tmp",FILE);return{imported:rows.length,proxies:catalog()}}
export const catalog=():SafeProxy[]=>load().map(({id,country,code,flag})=>({id,country,code,flag}));
export const record=(id:string)=>load().find(x=>x.id===id);
function sign(body:string){return crypto.createHmac("sha256",config.jwtSecret).update(body).digest("hex")}
export function issueReceipt(id:string){const r=record(id);if(!r)throw Error("proxy not found");const body=Buffer.from(JSON.stringify({id,endpoint:crypto.createHash("sha256").update(r.endpoint).digest("hex"),exp:Date.now()+TTL})).toString("base64url");return body+"."+sign(body)}
export function verifyReceipt(id:string,receipt:string){try{const[b,s]=receipt.split(".");const e=sign(b);if(!s||s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return false;const p=JSON.parse(Buffer.from(b,"base64url").toString());const r=record(id);return!!r&&p.id===id&&p.exp>=Date.now()&&p.endpoint===crypto.createHash("sha256").update(r.endpoint).digest("hex")}catch{return false}}
const once=<T>(em:NodeJS.EventEmitter,event:string)=>new Promise<T>((resolve,reject)=>{em.once(event,resolve);em.once("error",reject)});
async function exact(socket:net.Socket,n:number){let out=Buffer.alloc(0);while(out.length<n){const chunk=socket.read(n-out.length) as Buffer|null;if(chunk){out=Buffer.concat([out,chunk]);continue}await new Promise<void>((resolve,reject)=>{socket.once("readable",resolve);socket.once("error",reject);socket.once("end",()=>reject(Error("closed")))})}return out}
async function connectTcp(host:string,port:number){const s=net.connect(port,host);s.setTimeout(8000,()=>s.destroy(Error("timeout")));await once(s,"connect");return s}
async function httpTunnel(r:ProxyRecord,target:string,port:number,tlsToProxy:boolean){let base=await connectTcp(r.host,r.port);let s:net.Socket=base;if(tlsToProxy){s=tls.connect({socket:base,servername:net.isIP(r.host)?undefined:r.host,rejectUnauthorized:false});await once(s,"secureConnect")}const auth=r.username||r.password?`Proxy-Authorization: Basic ${Buffer.from(r.username+":"+r.password).toString("base64")}\r\n`:"";s.write(`CONNECT ${target}:${port} HTTP/1.1\r\nHost: ${target}:${port}\r\n${auth}Connection: keep-alive\r\n\r\n`);let data=Buffer.alloc(0);while(!data.includes(Buffer.from("\r\n\r\n"))){data=Buffer.concat([data,await once<Buffer>(s,"data")]);if(data.length>32768)throw Error("CONNECT response too large")}if(!/^HTTP\/1\.[01] 2\d\d /.test(data.toString("latin1"))){s.destroy();throw Error("CONNECT rejected")}s.setTimeout(0);return s}
async function socksTunnel(r:ProxyRecord,target:string,port:number){const s=await connectTcp(r.host,r.port);const auth=!!(r.username||r.password);s.write(auth?Buffer.from([5,2,0,2]):Buffer.from([5,1,0]));let x=await exact(s,2);if(x[1]===2){const u=Buffer.from(r.username),p=Buffer.from(r.password);s.write(Buffer.concat([Buffer.from([1,u.length]),u,Buffer.from([p.length]),p]));x=await exact(s,2);if(x[1]!==0)throw Error("SOCKS auth failed")}else if(x[1]!==0)throw Error("SOCKS method rejected");const h=Buffer.from(target);s.write(Buffer.concat([Buffer.from([5,1,0,3,h.length]),h,Buffer.from([port>>8,port&255])]));x=await exact(s,4);if(x[1]!==0)throw Error("SOCKS connect failed");const at=x[3];if(at===1)await exact(s,6);else if(at===4)await exact(s,18);else if(at===3){const n=(await exact(s,1))[0];await exact(s,n+2)}s.setTimeout(0);return s}
export async function connectViaProxy(r:ProxyRecord,target:string,port:number){if(r.protocol==="socks5")return socksTunnel(r,target,port);const modes=r.protocol==="https"?(net.isIP(r.host)?[false,true]:[true,false]):[false];let err:unknown;for(const tlsMode of modes){try{return await httpTunnel(r,target,port,tlsMode)}catch(e){err=e}}throw err||Error("proxy failed")}
async function probe(r:ProxyRecord,target:string){const started=Date.now();let raw:net.Socket|undefined;try{raw=await connectViaProxy(r,target,443);const s=tls.connect({socket:raw,servername:target,rejectUnauthorized:true});await once(s,"secureConnect");s.write(`GET / HTTP/1.1\r\nHost: ${target}\r\nConnection: close\r\n\r\n`);const head=(await once<Buffer>(s,"data")).toString("latin1");const status=Number(head.match(/^HTTP\/\d(?:\.\d)? (\d{3})/)?.[1]||0);s.destroy();return{target:"https://"+target,ok:status>=200&&status<400,status,latency_ms:Date.now()-started}}catch(e){raw?.destroy();return{target:"https://"+target,ok:false,status:null,latency_ms:Date.now()-started,error:(e as Error).name}}}
export async function testProxy(id:string){const r=record(id);if(!r)throw Error("proxy not found");const checks=await Promise.all([probe(r,"cloudflare.com"),probe(r,"google.com")]);const ok=checks.every(x=>x.ok);return{ok,proxy_id:id,country:r.country,flag:r.flag,checks,tested_at:new Date().toISOString(),receipt:ok?issueReceipt(id):null}}
