import net from "node:net";
import { config } from "./config.js";
import { connectViaProxy, record } from "./proxies.js";
import type { UserWithInbounds } from "./types.js";

const servers = new Map<number, net.Server>();
export function bridgePortForUser(userId:number){const port=config.proxyBridgeBasePort+userId;if(port>65535)throw Error("proxy bridge port range exhausted");return port}
async function readExact(socket:net.Socket,n:number){let out=Buffer.alloc(0);while(out.length<n){const chunk=socket.read(n-out.length) as Buffer|null;if(chunk){out=Buffer.concat([out,chunk]);continue}await new Promise<void>((resolve,reject)=>{socket.once("readable",resolve);socket.once("error",reject);socket.once("end",()=>reject(Error("closed")))})}return out}
async function target(socket:net.Socket){const head=await readExact(socket,4);if(head[0]!==5||head[1]!==1)throw Error("unsupported SOCKS request");let host="";if(head[3]===1)host=[...(await readExact(socket,4))].join(".");else if(head[3]===3){const n=(await readExact(socket,1))[0];host=(await readExact(socket,n)).toString("utf8")}else if(head[3]===4){const b=await readExact(socket,16);host=Array.from({length:8},(_,i)=>b.readUInt16BE(i*2).toString(16)).join(":")}else throw Error("bad address type");const p=await readExact(socket,2);return{host,port:p.readUInt16BE(0)}}
function handler(userId:number,proxyId:string){return async(socket:net.Socket)=>{let upstream:net.Socket|undefined;try{const greeting=await readExact(socket,2);const methods=await readExact(socket,greeting[1]);if(greeting[0]!==5||!methods.includes(0))throw Error("SOCKS auth unsupported");socket.write(Buffer.from([5,0]));const dst=await target(socket);const selected=record(proxyId);if(!selected)throw Error("selected proxy missing");upstream=await connectViaProxy(selected,dst.host,dst.port);socket.write(Buffer.from([5,0,0,1,0,0,0,0,0,0]));socket.pipe(upstream);upstream.pipe(socket);const close=()=>{socket.destroy();upstream?.destroy()};socket.on("error",close);upstream.on("error",close)}catch{try{socket.write(Buffer.from([5,1,0,1,0,0,0,0,0,0]))}catch{}socket.destroy();upstream?.destroy()}}}
export async function syncProxyBridges(users:UserWithInbounds[]){const wanted=new Map<number,string>();for(const u of users){if(u.enabled&&u.proxy_id&&record(u.proxy_id))wanted.set(u.id,u.proxy_id)}for(const[id,s]of servers){if(!wanted.has(id)){await new Promise<void>(r=>s.close(()=>r()));servers.delete(id)}}for(const[id,pid]of wanted){const existing=servers.get(id) as (net.Server&{proxyId?:string})|undefined;if(existing?.proxyId===pid)continue;if(existing){await new Promise<void>(r=>existing.close(()=>r()));servers.delete(id)}const server=net.createServer(handler(id,pid)) as net.Server&{proxyId?:string};server.proxyId=pid;await new Promise<void>((resolve,reject)=>{server.once("error",reject);server.listen(bridgePortForUser(id),"127.0.0.1",()=>{server.off("error",reject);resolve()})});servers.set(id,server)}return{running:servers.size}}
export async function stopProxyBridges(){await Promise.all([...servers.values()].map(s=>new Promise<void>(r=>s.close(()=>r()))));servers.clear()}
